
[flyway]
locations = ["filesystem:/app/migrations"]


[environments.default]
locations = ["filesystem:/app/migrations"]
url = "jdbc:postgresql://localhost:5432/eventdb"
user = "admin"
password = "letmein"
